# Generated by Django 2.0.6 on 2019-05-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_address', models.CharField(blank=True, max_length=60, null=True)),
                ('address_address', models.CharField(blank=True, max_length=100, null=True)),
                ('post_num', models.CharField(blank=True, max_length=60, null=True)),
                ('telephone_num', models.CharField(blank=True, max_length=60, null=True)),
                ('phone_num', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookClassify',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, max_length=40, null=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'book_classify',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BookItem',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'book_item',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Booklist',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(blank=True, max_length=40, null=True)),
                ('author', models.CharField(blank=True, max_length=40, null=True)),
                ('market_price', models.CharField(blank=True, max_length=40, null=True)),
                ('publish_time', models.DateField(blank=True, null=True)),
                ('publish', models.CharField(blank=True, max_length=40, null=True)),
                ('sales', models.BigIntegerField(blank=True, null=True)),
                ('edition', models.CharField(blank=True, max_length=40, null=True)),
                ('font_num', models.BigIntegerField(blank=True, null=True)),
                ('page', models.BigIntegerField(blank=True, null=True)),
                ('print', models.DateField(blank=True, null=True)),
                ('format', models.CharField(blank=True, max_length=40, null=True)),
                ('print_num', models.CharField(blank=True, max_length=40, null=True)),
                ('paper', models.CharField(blank=True, max_length=40, null=True)),
                ('isbn', models.CharField(blank=True, db_column='ISBN', max_length=40, null=True)),
                ('package', models.CharField(blank=True, max_length=40, null=True)),
                ('author_intro', models.CharField(blank=True, max_length=2000, null=True)),
                ('content', models.CharField(blank=True, max_length=2000, null=True)),
                ('recommend', models.CharField(blank=True, max_length=2000, null=True)),
                ('inventory', models.CharField(blank=True, max_length=40, null=True)),
                ('list', models.CharField(blank=True, max_length=2000, null=True)),
                ('book_pic', models.CharField(blank=True, max_length=2000, null=True)),
                ('two_category', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'booklist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('order_num', models.BigIntegerField()),
                ('sub_price', models.FloatField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('column_8', models.CharField(blank=True, db_column='Column_8', max_length=10, null=True)),
            ],
            options={
                'db_table': 'order_list',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('password', models.CharField(blank=True, max_length=40, null=True)),
                ('status', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
