# Generated by Django 2.0.6 on 2019-05-25 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190525_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='has_confirm',
            field=models.BooleanField(default=False, verbose_name='是否确认'),
        ),
    ]
