# Generated by Django 2.0.6 on 2019-05-25 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20190525_2222'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='confirm_string',
            table='t_Confirm_string',
        ),
    ]
